"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Endpoints = exports.PageFields = exports.CategoryFields = exports.PostFields = void 0;
// Enum declarations
var PostFields;
(function (PostFields) {
    PostFields["author"] = "author";
    PostFields["categories"] = "categories";
    PostFields["comment_status"] = "comment_status";
    PostFields["content"] = "content";
    PostFields["date"] = "date";
    PostFields["date_gmt"] = "date_gmt";
    PostFields["excerpt"] = "excerpt";
    PostFields["featured_media"] = "featured_media";
    PostFields["format"] = "format";
    PostFields["guid"] = "guid";
    PostFields["id"] = "id";
    PostFields["link"] = "link";
    PostFields["meta"] = "meta";
    PostFields["modified"] = "modified";
    PostFields["modified_gmt"] = "modified_gmt";
    PostFields["ping_status"] = "ping_status";
    PostFields["slug"] = "slug";
    PostFields["status"] = "status";
    PostFields["sticky"] = "sticky";
    PostFields["tags"] = "tags";
    PostFields["template"] = "template";
    PostFields["title"] = "title";
    PostFields["type"] = "type";
})(PostFields || (exports.PostFields = PostFields = {}));
var CategoryFields;
(function (CategoryFields) {
    CategoryFields["count"] = "count";
    CategoryFields["description"] = "description";
    CategoryFields["id"] = "id";
    CategoryFields["link"] = "link";
    CategoryFields["meta"] = "meta";
    CategoryFields["parent"] = "parent";
    CategoryFields["name"] = "name";
    CategoryFields["slug"] = "slug";
    CategoryFields["taxonomy"] = "taxonomy";
})(CategoryFields || (exports.CategoryFields = CategoryFields = {}));
var PageFields;
(function (PageFields) {
    PageFields["author"] = "author";
    PageFields["comment_status"] = "comment_status";
    PageFields["content"] = "content";
    PageFields["date"] = "date";
    PageFields["date_gmt"] = "date_gmt";
    PageFields["excerpt"] = "excerpt";
    PageFields["featured_media"] = "featured_media";
    PageFields["generated_slug"] = "generated_slug";
    PageFields["guid"] = "guid";
    PageFields["id"] = "id";
    PageFields["link"] = "link";
    PageFields["menu_order"] = "menu_order";
    PageFields["meta"] = "meta";
    PageFields["modified"] = "modified";
    PageFields["modified_gmt"] = "modified_gmt";
    PageFields["password"] = "password";
    PageFields["permalink_template"] = "permalink_template";
    PageFields["ping_status"] = "ping_status";
    PageFields["slug"] = "slug";
    PageFields["status"] = "status";
    PageFields["template"] = "template";
    PageFields["title"] = "title";
    PageFields["type"] = "type";
})(PageFields || (exports.PageFields = PageFields = {}));
var Endpoints;
(function (Endpoints) {
    Endpoints["blockDirectoryItems"] = "block-directory/search";
    Endpoints["blockRenderer"] = "block-rendered";
    Endpoints["blockRevisions"] = "<id>/autosaves";
    Endpoints["blocks"] = "blocks";
    Endpoints["blockTypes"] = "block-types";
    Endpoints["categories"] = "categories";
    Endpoints["comments"] = "comments";
    Endpoints["media"] = "media";
    Endpoints["pages"] = "pages";
    Endpoints["pageRevisions"] = "pages/<id>/revisions";
    Endpoints["plugins"] = "plugins";
    Endpoints["postRevisions"] = "posts/<id>/revisions";
    Endpoints["posts"] = "posts";
    Endpoints["postStatuses"] = "statuses";
    Endpoints["postTypes"] = "types";
    Endpoints["search"] = "search";
    Endpoints["settings"] = "settings";
    Endpoints["tags"] = "tags";
    Endpoints["taxonomies"] = "taxonomies";
    Endpoints["themes"] = "themes";
    Endpoints["users"] = "users";
})(Endpoints || (exports.Endpoints = Endpoints = {}));
